### ISSUE TITLE
引用时提示"Zotero整合错误”

### ISSUE THREAD

**Issue by Sicjall** [MuiseDestiny/zotero-citation#11]
感谢作者开发这个插件。现在遇到一个问题：按 ’ 键引用时，或者按shift+P引用的时候，都会弹出”Zotero整合错误"的提示，导致没法直接从Zotero引用到word。
![image](https://user-images.githubusercontent.com/105228384/218710780-18d54a35-2657-47ab-9fac-612df84d5ba3.png)

**Comment by MuiseDestiny** [comment]
解决了吗

**Comment by she529** [comment]
> 感谢作者开发这个插件。现在遇到一个问题：按 ’ 键引用时，或者按shift+P引用的时候，都会弹出”Zotero整合错误"的提示，导致没法直接从Zotero引用到word。 ![image](https://user-images.githubusercontent.com/105228384/218710780-18d54a35-2657-47ab-9fac-612df84d5ba3.png)

这个应该是通讯得问题  用管理员权限打开zzotero可能不会报错了
