### ISSUE TITLE
zotero提示Warning: The Zotero plugin for Microsoft Word is outdated.

### ISSUE THREAD

**Issue by pencilheart** [MuiseDestiny/zotero-citation#125]
当采用`'`进行插入文献时，zotero提示：“The Zotero plugin for Microsoft Word is outdated. Reinstall the plugin from Preferences → Cite → Word Processors.”
![Xnip2024-01-18_11-08-19](https://github.com/MuiseDestiny/zotero-citation/assets/61617063/6c4cb7bc-de5f-442e-86ff-7987e1a836cc)

系统：macOS 14.2.1
Zotero：7.0.0-beta.54+6b996d4f9
zotero-citation插件：0.4.2

**Comment by DontKnowL** [comment]
同样的问题，重新安装或者卸载加载项后重装都不行

**Comment by pencilheart** [comment]
fixed in 0.4.7
