### ISSUE TITLE
插入文献后引用文献更新问题

### ISSUE THREAD

**Issue by she529** [MuiseDestiny/zotero-citation#13]
这个插件真的很好用，非常感谢作者。

最近在写大论文，需要插入的参考文献比较多，发现一个问题：

每次插入文献后，citation中的引用信息都需要更新一次，当插入的文献较多的时候，更新的时间会很长，在引用信息更新期间是不能进行插入其他文献的操作的，只能等数据更新完才能插入新的文献。

改进：能否将生成citation文件功能设置为可选功能，当需要的时候再生成citation引用数据，而在其他时候可以选择不生成。

**Comment by MuiseDestiny** [comment]
可能是因为有一个逻辑我没有优化，导致频繁更新（因为测试都是少量引用，就没特意优化）。

> 在引用信息更新期间是不能进行插入其他文献的操作的

意思是按引号键没有反应吗，还是其它的。

**Comment by MuiseDestiny** [comment]
> > 可能是因为有一个逻辑我没有优化，导致频繁更新（因为测试都是少量引用，就没特意优化）。
> > > 在引用信息更新期间是不能进行插入其他文献的操作的
> > 
> > 
> > 意思是按引号键没有反应吗，还是其它的。
> 
> 不是，就是每次插入文献后，需要等待citation中引用信息的更新，我现在大概100篇文献，引用编号的数据更新时间快1分钟了

明白了，我优化一下编号更新。然后测试时候也用100篇测试。

**Comment by she529** [comment]
> 

辛苦大佬

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-citation/releases/tag/0.1.2
已解决，测试没问题可以关闭此问题

**Comment by she529** [comment]
> https://github.com/MuiseDestiny/zotero-citation/releases/tag/0.1.2 已解决，测试没问题可以关闭此问题
等待的时间感觉短了一点 但还是需要等待，感觉把生成引用数据的功能单独出来，比如添加到查看中，可选择生成会不会比较好？插入文献使用的频率会比较多，而查看引用信息的频率相对较少。不是很了解zotero插件的开发，不知道实现起来容易不容易。
但是还是要谢谢大佬！！

**Comment by MuiseDestiny** [comment]
> 感觉把生成引用数据的功能单独出来

在执行刷新，插入文献时候，这个功能其实就是被关闭了的，如果还感觉慢，应该是Zotero的插入本来就慢。

比如在word执行插入文献操作，插件不会刷新那个临时文件夹，等到插入结束后才会刷新。之前说的`只能等数据更新完才能插入新的文献`是因为插入过程中也更新这个临时文件夹导致的。

总结，那个文件夹对插入文献过程没有任何影响的，如果还感觉慢，可以试试关闭插件，在word插入，看看反应时间。

**Comment by MuiseDestiny** [comment]
> > https://github.com/MuiseDestiny/zotero-citation/releases/tag/0.1.2 已解决，测试没问题可以关闭此问题
> 
> 等待的时间感觉短了一点 但还是需要等待，感觉把生成引用数据的功能单独出来，比如添加到查看中，可选择生成会不会比较好？插入文献使用的频率会比较多，而查看引用信息的频率相对较少。不是很了解zotero插件的开发，不知道实现起来容易不容易。 但是还是要谢谢大佬！！

可以录一个视频，对比下不用插件的引用过程，和使用插件的引用过程的对比吗。可以排除Zotero本身就很慢。

**Comment by MuiseDestiny** [comment]
https://user-images.githubusercontent.com/51939531/219565837-80af5ef7-c3eb-4060-bd9b-df05f177f9d9.mp4

我使用过程中，这个速度与不安装是一样的。

**Comment by she529** [comment]
> 我使用过程中，这个速度与不安装是一样的。

https://user-images.githubusercontent.com/75371769/219713998-d02a4050-5b84-44aa-8a1b-bf35e5d58b8d.mp4

不好意思 白天有事没来得及说  出现的这个问题可能不是更新引用数据的问题  大概的情况就是使用快捷键添加完引用文献后，先出现进度条  然后在word中 其实已经添加好引用数据了  但是此时在zotero中 是不能选择其他文献的  得等一段时间

**Comment by she529** [comment]
> 实已经添加好引用数据了 但是此时在zotero中 是不能选择其他文献的 得等一段时间



> > 我使用过程中，这个速度与不安装是一样的。
> 
> 不好意思 白天有事没来得及说 出现的这个问题可能不是更新引用数据的问题 大概的情况就是使用快捷键添加完引用文献后，先出现进度条 然后在word中 其实已经添加好引用数据了 但是此时在zotero中 是不能选择其他文献的 得等一段时间

从视频得第4秒开始  选择其他文献 就会自动跳回到刚刚插入得文献上  直到视频最后才恢复正常   之前以为是更新数据  但是现在有可能不是  大佬可以确认下

**Comment by MuiseDestiny** [comment]
我知道原因了，是刷新的问题。我设置了刷新，可能电脑体质原因，你的设备疯狂执行刷新。我去掉刷新就好了。

**Comment by she529** [comment]
> 我知道原因了，是刷新的问题。我设置了刷新，可能电脑体质原因，你的设备疯狂执行刷新。我去掉刷新就好了。

大佬辛苦

**Comment by she529** [comment]
> 我知道原因了，是刷新的问题。我设置了刷新，可能电脑体质原因，你的设备疯狂执行刷新。我去掉刷新就好了。

完美解决

**Comment by MuiseDestiny** [comment]
> > 我知道原因了，是刷新的问题。我设置了刷新，可能电脑体质原因，你的设备疯狂执行刷新。我去掉刷新就好了。
> 
> 完美解决

解决了吗，我还没去除刷新主要是。

**Comment by she529** [comment]
> > > 我知道原因了，是刷新的问题。我设置了刷新，可能电脑体质原因，你的设备疯狂执行刷新。我去掉刷新就好了。
> > 
> > 
> > 完美解决
> 
> 解决了吗，我还没去除刷新主要是。

测试不准确  测试得时候添加得是已经引用过得  所以很快 没有刷新情况  发现添加已经引用得文献 就不会疯狂刷新  添加新的文献引用  就会出现这种问题

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-citation/releases/tag/0.1.2-1
试试这个

**Comment by she529** [comment]
> https://github.com/MuiseDestiny/zotero-citation/releases/tag/0.1.2-1 试试这个

没问题了   辛苦大佬
