### ISSUE TITLE
插入文献后，好像出了个严重bug 无法选中其他分类，

### ISSUE THREAD

**Issue by she529** [MuiseDestiny/zotero-citation#14]
最新版本的cita

https://user-images.githubusercontent.com/75371769/220641824-805628f4-71d1-4e7f-b46b-0407670535a9.mp4

**Comment by MuiseDestiny** [comment]
一直这种情况吗，有个刷新我没限制，可能这里他一直在刷新所以点击不了。但我电脑上正常的。

**Comment by she529** [comment]
> 一直这种情况吗，有个刷新我没限制，可能这里他一直在刷新所以点击不了。但我电脑上正常的。

重启下就好了  导致的原因也可能是我把生成的引用文件夹删掉了 ？但是用之前的版本没出现这个问题

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-citation/releases/tag/0.1.5

我上传了一个刷新间隔1s的版本。

之前版本之刷新一次。最新版可能比较激进，citation-1是保守的。

**Comment by she529** [comment]
> https://github.com/MuiseDestiny/zotero-citation/releases/tag/0.1.5
> 
> 我上传了一个刷新间隔1s的版本。
> 
> 之前版本之刷新一次。最新版可能比较激进，citation-1是保守的。

我试试

**Comment by she529** [comment]
> > https://github.com/MuiseDestiny/zotero-citation/releases/tag/0.1.5
> > 我上传了一个刷新间隔1s的版本。
> > 之前版本之刷新一次。最新版可能比较激进，citation-1是保守的。
> 
> 我试试

不知道是不是上面说的那个刷新的问题，但是大概率可能和生成引用数据文件有关  我发现着这种情况都出现在我有两个引用数据文件夹  然后我删除或者对数据文件夹进行操作的时候就回出现这种情况  但是不是每次都出现  出现后重启zotero 或者把插件关了重新安装一次就好了

**Comment by she529** [comment]
> > > https://github.com/MuiseDestiny/zotero-citation/releases/tag/0.1.5
> > > 我上传了一个刷新间隔1s的版本。
> > > 之前版本之刷新一次。最新版可能比较激进，citation-1是保守的。
> > 
> > 
> > 我试试
> 
> 不知道是不是上面说的那个刷新的问题，但是大概率可能和生成引用数据文件有关 我发现着这种情况都出现在我有两个引用数据文件夹 然后我删除或者对数据文件夹进行操作的时候就回出现这种情况 但是不是每次都出现 出现后重启zotero 或者把插件关了重新安装一次就好了

或者有没有什么办法能看到哪里出错了   zotero带的调试日志ok不？

**Comment by she529** [comment]
> > > > https://github.com/MuiseDestiny/zotero-citation/releases/tag/0.1.5
> > > > 我上传了一个刷新间隔1s的版本。
> > > > 之前版本之刷新一次。最新版可能比较激进，citation-1是保守的。
> > > 
> > > 
> > > 我试试
> > 
> > 
> > 不知道是不是上面说的那个刷新的问题，但是大概率可能和生成引用数据文件有关 我发现着这种情况都出现在我有两个引用数据文件夹 然后我删除或者对数据文件夹进行操作的时候就回出现这种情况 但是不是每次都出现 出现后重启zotero 或者把插件关了重新安装一次就好了
> 
> 或者有没有什么办法能看到哪里出错了 zotero带的调试日志ok不？

确定造成这种情况的流程是我在word带的zotero点击refresh 后出现的  第一刷新生成的引用数据文件夹名字是随机生成的  这时候是没有问题的  第二次刷新名字变成word的名字 这个时候就出现视频里的bug

**Comment by she529** [comment]
https://user-images.githubusercontent.com/75371769/221418697-fa32203d-c918-4f5c-a87a-a1fff157a136.mp4

**Comment by she529** [comment]
> 

53秒左右的那次刷新后就出现问题了  很奇怪

**Comment by she529** [comment]
> > https://github.com/MuiseDestiny/zotero-citation/releases/tag/0.1.5
> > 我上传了一个刷新间隔1s的版本。
> > 之前版本之刷新一次。最新版可能比较激进，citation-1是保守的。
> 
> 我试试

刷新1s的这个版本也同样出现这种问题

**Comment by she529** [comment]
> > > https://github.com/MuiseDestiny/zotero-citation/releases/tag/0.1.5
> > > 我上传了一个刷新间隔1s的版本。
> > > 之前版本之刷新一次。最新版可能比较激进，citation-1是保守的。
> > 
> > 
> > 我试试
> 
> 刷新1s的这个版本也同样出现这种问题

已经完全用不了了   不知道是不是因为zotero最新版本和插件有冲突？  已经醉了

**Comment by MuiseDestiny** [comment]
* 复现了此bug，已修复

bug语句（已移除）：
这是一个分类刷新函数，但不知道为什么会引发分类锁定问题，本来写这句是为了刷新更快（弄巧成拙了）
```js
ZoteroPane.collectionsView.refresh()
```
* 优化了数据储存，不覆盖`其它`原有的内容

https://github.com/MuiseDestiny/zotero-citation/releases/new
