### ISSUE TITLE
引用列功能和其他插件不兼容

### ISSUE THREAD

**Issue by GladysKao** [MuiseDestiny/zotero-citation#146]
打开这三个插件中的任意一个都不能正常打开引用列了，求修复
![Snipaste_2024-09-22_00-05-49](https://github.com/user-attachments/assets/2b2b235e-9092-4349-83f8-80c9dafa7409)
这三个插件和citation插件以及zotero(x64)全部都是最新换的最新版

**Comment by MuiseDestiny** [comment]
请升级插件，重点style（4.9.6：https://gitee.com/MuiseDestiny/plugins/blob/master/zotero-style.xpi）和translate（2.0.1）
