### ISSUE TITLE
刚更新到zotero7，安装最新版的zotero citation没有效果

### ISSUE THREAD

**Issue by RorschachY** [MuiseDestiny/zotero-citation#151]
zotero6使用没问题，刚更新到zotero7，安装最新版的zotero citation没有效果
没有出现引用列
![Quicker_20241012_215225](https://github.com/user-attachments/assets/3d629b2a-c396-4f3c-8bbc-389afd0a2f46)

按引用号也无法引用，拖动会显示
![Quicker_20241012_215301](https://github.com/user-attachments/assets/afe24d41-42f9-4f10-a5fc-dd4b71900be0)

**Comment by RorschachY** [comment]
![image](https://github.com/user-attachments/assets/d5ea4682-ca55-453c-b1f3-97aa2131b5f0)
这是目前zotero的版本

**Comment by kanonazuko** [comment]
我也是这个情况

**Comment by tjuyyz** [comment]
使用0.4.0版本可以

**Comment by Calvaire** [comment]
请问如何解决的，我也遇到了同样的问题

**Comment by RorschachY** [comment]
> 请问如何解决的，我也遇到了同样的问题

重装几次之后就好了

**Comment by ZShuai95** [comment]
还是不行呀
