### ISSUE TITLE
Missing Citation Column in Latest Zotero Plugin Version on Windows 10 

### ISSUE THREAD

**Issue by gthanmon** [MuiseDestiny/zotero-citation#154]
The latest version of the plugin does not display the citation column in the latest version of Zotero on Windows 10, while version 0.4.0 of the plugin functions properly.

最新版本插件在最新版zotero上没有引用列，win10系统， 0.4.0版本插件则可以正常运行

**Comment by Calvaire** [comment]
我这边WIN10是可以的，WIN11反倒不行，很奇怪

**Comment by gthanmon** [comment]
最新版0.4.7问题依旧

**Comment by Calvaire** [comment]
> 最新版0.4.7问题依旧

我倒是修好了，出现引用列了

**Comment by MuiseDestiny** [comment]
> 遇到了同样的问题，但0.4.0存在的问题是在Zotero中随意拖动也会生成引用。

https://github.com/MuiseDestiny/zotero-citation/releases/tag/0.4.8

**Comment by gthanmon** [comment]
> > 最新版0.4.7问题依旧
> 
> 我倒是修好了，出现引用列了

咋弄的

**Comment by gthanmon** [comment]
> > 遇到了同样的问题，但0.4.0存在的问题是在Zotero中随意拖动也会生成引用。
> 
> https://github.com/MuiseDestiny/zotero-citation/releases/tag/0.4.8

最新版终于可以正常用了
