### ISSUE TITLE
增加功能建议

### ISSUE THREAD

**Issue by songtengfei95** [MuiseDestiny/zotero-citation#18]
大佬您好，在zotero生成的临时文件夹中虽然会包含word中插入的文献，但是没有序号标识，比如我想回看第18篇文献是哪个，需要回到文档末尾在参考文献目录中查看。那如果在生成的参考文献临时文件夹中有一列显示此文献在word引用中的序号，将会方便许多。

十分感谢大佬插件，一个小小建议不知道能否实现。

**Comment by MuiseDestiny** [comment]
你好，本身是有这个功能的，是严格按照引用顺序排序的。
![image](https://user-images.githubusercontent.com/51939531/223896883-bc15576d-f082-4033-b442-1d6995907aff.png)

**Comment by MuiseDestiny** [comment]
某一篇文献在word里所参与的引用，都会在引用列展示出来。并且从上到下（如果按照引用列排序），和引用顺序一一对应的。

比如截图，第一篇第二篇都有[1, 2]，那么第二篇就是[1, 2]里的2。

**Comment by songtengfei95** [comment]
哇塞，调出“引用”后看到了，非常感谢，这个插件真棒！
