### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by 1067237855** [MuiseDestiny/zotero-citation#23]
## 出现以下弹窗
>在 Word 中将光标定位到待插入引用的位置，在 Zotero 中选择条目后按键盘上的 ' 键
>在 Zotero 中拖拽（鼠标按下）待引用的条目（可多选）拖拽到 Word 中需要添加引用的位置（松开鼠标）。

![image](https://user-images.githubusercontent.com/104330036/226084452-0b53a1d5-db6a-43fe-a83c-d07ed8622878.png)
点击OK则进入了https://www.zotero.org/support/kb/debugging_broken_documents

## 按 `Shift + P` 打开命令行工具，没有 `引用` 命令
![image](https://user-images.githubusercontent.com/104330036/226084494-15123780-0dd7-4a8a-ab8b-c6cb8ad2d48e.png)

## 左侧栏自动出现以下内容
PS:要插入文献的word文档其名称为“朋朋师兄毕业论文模板.docx”
![image](https://user-images.githubusercontent.com/104330036/226084754-82dd602b-0e97-47e1-960e-5e5c5e3258c6.png)

插件均为最新版
以前该插件是可以正常使用的（两周前安装的citation-0.2.0是可以正常使用的），个人认为是style或reference的原因导致的

**Comment by MuiseDestiny** [comment]
一会更新下

**Comment by MuiseDestiny** [comment]
试了下，不存在冲突。

-1是重新编译的

![image](https://user-images.githubusercontent.com/51939531/226089873-b4cde1c6-88b2-45a7-aa1f-4a12e0f78c12.png)

**Comment by wisejky** [comment]
好像还是不行呢？

**Comment by wisejky** [comment]
> 

按引号可以，shift+p没反应

**Comment by MuiseDestiny** [comment]
> > 
> 
> 按引号可以，shift+p没反应

放弃shif p吧，下个版本就把他删除。拖拽和引号键明显更快速

**Comment by 1067237855** [comment]
> 好像还是不行呢？

重新安装citation插件，重启word和zotero就好了，我的没有问题了

**Comment by 1067237855** [comment]
citation-0.2.1 BUG：  `引用列` 不显示  [文献编号] 

![image](https://user-images.githubusercontent.com/104330036/226348459-377f41ab-acf3-44b6-a3a6-0ebc3e716646.png)


另外，[0.2.1: Word生成分类支持搜索](https://github.com/MuiseDestiny/zotero-citation/releases/tag/0.2.1)  没看明白更新了啥功能，不知道咋用

**Comment by MuiseDestiny** [comment]
就是修复bug属于是。整理的文献本身应该支持搜索的，但是上一个版本怎么搜都不变。

**Comment by MuiseDestiny** [comment]
引用列不显示应该属于个例，我设备显示没问题。可以创建一个新的word，插入几个引用，再刷新试试

**Comment by 1067237855** [comment]
尝试了重启word和zotero，并新建word，依旧  `引用列` 不显示 [文献编号]
而且，下图中 有几个图标 显示异常，都变成word图标了
![image](https://user-images.githubusercontent.com/104330036/226354511-f69a1704-0d0e-4802-ad8d-82b1f033fdb8.png)

> 引用列不显示应该属于个例，我设备显示没问题。可以创建一个新的word，插入几个引用，再刷新试试

**Comment by MuiseDestiny** [comment]
稍等马上修复

**Comment by MuiseDestiny** [comment]
知道原因了

**Comment by MuiseDestiny** [comment]
记得要把前缀去掉，忘了去了。改成word图表没必要用前缀了，也就是你图中的undefined

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/226356952-8d30084e-358c-4aac-b889-8ee56c91be97.png)

支持的这里的搜索（本应该就支持的）

**Comment by 1067237855** [comment]
稍等，现在还是有问题，我重启电脑看看

**Comment by MuiseDestiny** [comment]
我再上传一版

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-citation/releases/tag/0.2.2

**Comment by 1067237855** [comment]
![image](https://user-images.githubusercontent.com/104330036/226363673-4604cc66-0a8c-4f4e-883b-967c902f5733.png)
大佬稳一手，还是得详细排查一下。大佬你那边好使不？不知道其它人有没有这个问题

**Comment by MuiseDestiny** [comment]
离谱了，我再测试下哈

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.5.2

更新，把logo优化了，扁扁的按钮太难看了

**Comment by deulofeu1** [comment]
我也遇到了这个问题，禁用style后重新打开refresh就好了

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-style/releases/tag/2.5.3

已解决
