### ISSUE TITLE
插件导致同步失效

### ISSUE THREAD

**Issue by llity** [MuiseDestiny/zotero-citation#31]
现在禁用所有插件都不能同步。帮忙看看是什么引起的呢？谢谢
`
[JavaScript Error: "reader is undefined" {file: "chrome://zotero-night/content/zotero-night.js" line: 989}]

[JavaScript Error: "Error 400 for search ZQZGHSQ4 in My Library:

ZoteroObjectUploadError: Search name cannot be empty"]
`
<img width="413" alt="image" src="https://user-images.githubusercontent.com/11771112/231131190-ecd79d93-9f1c-4abf-82d4-af8262b1fb7b.png">

**Comment by MuiseDestiny** [comment]
没有名称的文件夹是可以在Zotero里看到的吗

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-citation/blob/bootstrap/src/modules/citation.ts#L156

```ts
public async initSearch(sessionID: string) {
		let search = new Zotero.Search();
		search.addCondition("title", "contains", "");
		await search.search();
		search.name = sessionID
		const session: SessionData =  this.sessions[sessionID]
		session.search = search = search.clone(1)
		await search.saveTx({ skipSelect: true })
		this.filterFunctions.push(
			(items: Zotero.Item[]) => {
				// 当前处在伪搜索文件夹中才进行拦截
				let selectedSearch = ZoteroPane.collectionsView.getSelectedSearch()
				if (selectedSearch.key == search.key) {
					const ids = Object.keys(session.idData).map(id => Number(id))
					return items.filter(item=>ids.indexOf(item.id) != -1)
				} else {
					return items
				}
			}	
		)
		window.setTimeout(async () => {
			await this.clearSearch()
		}, 233)
	}
```
原因是这个函数接收的sessionID是undefined，等适配Mac，就不会有这个bug了。

**Comment by llity** [comment]
> > > 我是插件开发者，不是Zotero软件开发者
> > 
> > 
> > 破案了：citation创建了没有名称的文件夹，删除文件夹就能同步了。 [forums.zotero.org/discussion/comment/432447#Comment_432447](https://forums.zotero.org/discussion/comment/432447#Comment_432447) Yeah，it's the one of the plugin called"zotero citation" [muisedestiny/zotero-citation#readme](https://github.com/muisedestiny/zotero-citation#readme) The author declared the possible disfunction on Mac, because the author don't have device based on Mac Os. So when i dragged the article into word to cite, a purple citation folder was created. I think that is the reason folders without names were created, and sync stopped.
> 
> sorry，还真是citation问题，我有时间尝试适配mac

插件都非常实用，昨日已赞赏 :) , 兼容性和稳定性继续加油。不知道后面升级Zotero v7在适配方便会不会有大的变化。

**Comment by llity** [comment]
> 没有名称的文件夹是可以在Zotero里看到的吗

有一个空名称的saved search文件夹，手动删除就能同步了。

**Comment by llity** [comment]
@MuiseDestiny 官方不知道是不是人手不足，免费软件，估计佛系更新，issues一大推。Zotero的稳定性堪忧，看V7怎么样。很多功能N年都没合并，比如meta update。缺少功能只能靠三方插件了，加油！

**Comment by MuiseDestiny** [comment]
> 

Ok，I will slove it.
