### ISSUE TITLE
加载插件以后，无法直接拖拽文件至新文件夹

### ISSUE THREAD

**Issue by sevvvvv** [MuiseDestiny/zotero-citation#32]
把其他插件全关了以后只加载citation还是有这个问题，关了citation就没事了

**Comment by MuiseDestiny** [comment]
0.3.1更新

citation为zotero加入`引用/citation`列
![image](https://user-images.githubusercontent.com/51939531/232370268-d581e8ef-1143-42b2-8443-864342492ef8.png)

当你打开引用列，代表你正在写word，此时拖拽：只能用于word引用。

如果想恢复Zotero的拖拽功能需要关闭`引用/citation`列。

**Comment by sevvvvv** [comment]
实测没有打开引用列，也没有打开word，还是不可以拖拽额

**Comment by MuiseDestiny** [comment]
> 实测没有打开引用列，也没有打开word，还是不可以拖拽额

更新到最新。重启。

**Comment by sevvvvv** [comment]
呦西，膜拜大佬
