### ISSUE TITLE
文献拖拽

### ISSUE THREAD

**Issue by tzycsu** [MuiseDestiny/zotero-citation#35]
无法拖拽文献到zotero的其它文件夹，我试了上一个版本可以的。

**Comment by MuiseDestiny** [comment]
看最新版发布说明，关闭引用列

**Comment by tzycsu** [comment]
谢谢已经解决了，
![image](https://user-images.githubusercontent.com/79492862/232647901-00a8a101-5cf6-477f-a574-6b6a06946726.png)
那这个是啥问题呢？显示不全，越把这一列拖动变大反而越来越小。

**Comment by tzycsu** [comment]
看见style的更新说明了，辛苦大佬了。

**Comment by MuiseDestiny** [comment]
> 看见style的更新说明了，辛苦大佬了。



> 谢谢已经解决了， ![image](https://user-images.githubusercontent.com/79492862/232647901-00a8a101-5cf6-477f-a574-6b6a06946726.png) 那这个是啥问题呢？显示不全，越把这一列拖动变大反而越来越小。

你插件里所有显示引用数量的插件都会导致这个bug，还有在首选下关闭style关系图谱试试
