### ISSUE TITLE
v0.3.1 zotero 条目无法通过鼠标拖动改变分组

### ISSUE THREAD

**Issue by lymyxhw** [MuiseDestiny/zotero-citation#36]
v0.3.1 导致无法使用鼠标拖动移动条目到别的分组内，我试过仅使用该插件时出现这个问题，请测试一下是否存在，感谢

**Comment by MuiseDestiny** [comment]
关闭引用列即可。

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-citation/releases/tag/0.3.1

**Comment by lymyxhw** [comment]
> 关闭引用列即可。

好的，谢谢！
