### ISSUE TITLE
Word中按引号没有反映

### ISSUE THREAD

**Issue by balalery** [MuiseDestiny/zotero-citation#42]
zotero和citation都是最新版的，zotero6.0.26，citation0.3.1

**Comment by MuiseDestiny** [comment]
在zotero选中条目后按引号

**Comment by balalery** [comment]
是的，我确实是这样做的

**Comment by MuiseDestiny** [comment]
> 是的，我确实是这样做的

todesk远程

**Comment by MuiseDestiny** [comment]
> ToDesk: 设备代码:946 930 762 临时密码:amq4ier5

好好的。一切正常。还不行建议认真阅读readme。

**Comment by balalery** [comment]
好的，非常感谢
