### ISSUE TITLE
在打开pdf预览器之后，加载完参考文献会导致与pdf-translate插件位置的冲突。显示的是“翻译”的位置，但是下面的条目是“参考文献”的内容。

### ISSUE THREAD

**Issue by Wilhenry777** [MuiseDestiny/zotero-citation#45]
<img width="431" alt="image" src="https://github.com/MuiseDestiny/zotero-citation/assets/103740440/20b01ad2-d50b-4198-942b-663fbdd6a158">

**Comment by MuiseDestiny** [comment]
这不是预览器，是抓取的pdf的参考文献。

在修复bug之前。可以先点击一下参考文献再点击翻译就好了。
