### ISSUE TITLE
自 Zotero 启动以来首次打开 Word 引文选择窗口时会显示两个当前文件的搜索结果合集

### ISSUE THREAD

**Issue by northword** [MuiseDestiny/zotero-citation#5]
感谢开发如此优秀的插件！使用过程中遇到一些小问题：

## 问题1

自 Zotero 启动以来首次打开 Word 引文选择窗口时会显示两个当前文件的搜索结果合集：

https://user-images.githubusercontent.com/44738481/215456864-40c07baa-a0ac-4db7-bc17-cc790de0b99c.mp4

第二次及之后就只有一个搜索结果 Collection 了：
![image](https://user-images.githubusercontent.com/44738481/215457151-9321677e-56fd-41bd-9ad1-5f533e9b73c9.png)

期望：首次打开时也仅显示一个搜索结果 Collection。

## 问题2

首次打开 Word 引文选择窗口时，无论打开前在 Zotero 里打开的是哪个 Collection，在 Word 引文选择窗口里都会被聚焦到搜索结果 Collection。（二次及之后正常）

原有的逻辑：引用前 Zotero 里正在浏览 Collection A，在 Word 里打开引文选择窗口时，保持在 Collection A。
期望：保持 Zotero 原有的逻辑。

## 问题3 

不知道我测试的对不对，现有的好像是在 Word 里点击 Add/edit citations 之后才开始创建搜索结果，仅仅打开一个存在引用的 Word 文档并不会出现该结果。有没有可能去捕获 Word 的进程，当存在 Word 进程时就检测打开文件中的引文？

**Comment by MuiseDestiny** [comment]
很清晰直观的问题描述！这样的问题十分有助于插件升级。

**问题一**我也有遇到过，然后优化了，只是没更新版本号，可以重新下载github最新版安装试试。

**问题二**我也发现了，需要优化，另外这个插件支持直接在Zotero里点击要引用的条目按引号键引用。

**问题三**首次打开word并不会与Zotero建立联系，需要刷新或插入一条文献后word和zotero才会通信。

https://github.com/MuiseDestiny/zotero-citation/releases/tag/0.0.4 已发布。

**Comment by northword** [comment]
收到，问题一已经解决，感谢！

> 另外这个插件支持直接在Zotero里点击要引用的条目按引号键引用。

试用了这个方法，很方便！

另外，在 EndNote 中，有一个拖拽条目到 Word 即可引用的行为，这个行为在 Zotero 里是 Zotero 自带的导出参考文献表，见下录屏描述，不知道插件能不能取代这个拖拽操作为插入引文呢？


https://user-images.githubusercontent.com/44738481/215470171-52e92497-4944-4e27-8f04-91e83610bed2.mp4

**Comment by 1067237855** [comment]
期待实现该功能！！！👍👍👍
> 另外，在 EndNote 中，有一个拖拽条目到 Word 即可引用的行为，这个行为在 Zotero 里是 Zotero 自带的导出参考文献表，见下录屏描述，不知道插件能不能取代这个拖拽操作为插入引文呢？

**Comment by MuiseDestiny** [comment]
https://user-images.githubusercontent.com/51939531/220584939-6d7ec109-46fd-424a-855e-d28f3b2c154a.mp4

如你所愿。

**Comment by MuiseDestiny** [comment]
> 有一个拖拽条目到 Word 即可引用的行为

实现了，但是zotero原本的拖拽粘贴文本就失效了。副作用不负责的。

**Comment by 1067237855** [comment]
> > 有一个拖拽条目到 Word 即可引用的行为
> 
> 实现了，但是zotero原本的拖拽粘贴文本就失效了。副作用不负责的。

小问题


牛逼👍👍👍👍👍效率👍👍👍👍👍点赞！！！！👍👍👍👍👍
