### ISSUE TITLE
拖拽导致的插入问题

### ISSUE THREAD

**Issue by Geo123abc** [MuiseDestiny/zotero-citation#50]
zotero版本：v6.0.26
插件版本：v0.3.1  或 v0.3.2

### 问题：
1. 之前往zotero自带的笔记中拖拽条目，是可以生成一个引用；现在如果Word开着，即使是拖拽到zotero自带的笔记中或者其它文档编辑器，释放之后也是在Word中插入引用文献，而不是在目标文档编辑器中插入引用文献；
2. 之前拖拽条目到其它分类也没问题；现在无法使用这个功能。
3. 禁用citation插件之后，上述两个问题解决了。

### 期待改进方案：
1. 拖拽时，是否能检测鼠标释放的位置，以区别不同功能？
2. 如果1无法实现，是否可以提供一个开关，让用户自己选择 开启/关闭 citation 插件的拖拽功能？

祝好。

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-citation#22-%E6%8B%96%E6%8B%BD%E5%BC%95%E7%94%A8

> 之前拖拽条目到其它分类也没问题；现在无法使用这个功能。
关闭`引用列`拖拽引用就会失效，就可以恢复

平时不要开启引用列，等到真的需要拖拽到word再开启。这也是为什么开启拖拽引用需要开启引用列的原因，这是破坏性的需要你确认。

**Comment by Geo123abc** [comment]
> https://github.com/MuiseDestiny/zotero-citation#22-%E6%8B%96%E6%8B%BD%E5%BC%95%E7%94%A8
> 
> > 之前拖拽条目到其它分类也没问题；现在无法使用这个功能。
> > 关闭`引用列`拖拽引用就会失效，就可以恢复
> 
> 平时不要开启引用列，等到真的需要拖拽到word再开启。这也是为什么开启拖拽引用需要开启引用列的原因，这是破坏性的需要你确认。

“初闻不知曲中意，再闻已是曲中人”，还是对产品不太了解，现在完美搞定，谢谢。
