### ISSUE TITLE
临时文件夹前面有个undefined

### ISSUE THREAD

**Issue by cesaryuan** [MuiseDestiny/zotero-citation#9]
![image](https://user-images.githubusercontent.com/35998162/218619662-8f79a4af-0407-45d0-87ab-32a1bfbaacaa.png)

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/218622729-74264606-413b-4a87-a9e1-5c7f8ba25144.png)

这里可能初始化失败了，手动设置下这个前缀

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/218623096-d65f5ef5-4d75-4d0f-b890-a3fcca9b4ca0.png)
或者重新下载一下最新版。

**Comment by cesaryuan** [comment]
OK啦
